FROM mongo:7.0

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint_primary.sh /entrypoint.sh
COPY migration.py /migration.py
COPY init-replica.js /init-replica.js
COPY mongo-keyfile /etc/mongo-keyfile

RUN chmod 400 /etc/mongo-keyfile && chown mongodb:mongodb /etc/mongo-keyfile
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
